name: Publish to NPM & GitHub Packages

on:
  workflow_dispatch:
    inputs:
      version_type:
        description: 'Version type'
        required: false
        type: choice
        options:
          - patch
          - minor
          - major
        default: 'patch'
      custom_version:
        description: 'Custom version - overrides version type'
        required: false
        type: string

permissions:
  contents: write
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      # Setup Node.js for npm registry
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'
      
      - run: npm ci
      - run: npm test
      
      - run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
      
      - run: |
          if [ -n "${{ github.event.inputs.custom_version }}" ]; then
            npm version ${{ github.event.inputs.custom_version }}
          else
            npm version ${{ github.event.inputs.version_type }}
          fi
      
      # Publish to npm
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      
      # Setup Node.js for GitHub Packages
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@thehuman00'
      
      # Update package.json for GitHub Packages
      - run: |
          npm pkg set name="@thehuman00/precise-time-ntp"
          npm pkg set publishConfig.registry="https://npm.pkg.github.com"
      
      # Publish to GitHub Packages
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      # Push version changes
      - run: git push --follow-tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}